# Generated by Django 4.2.7 on 2023-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforms', '0002_question_number_alter_survey_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
